### ISSUE TITLE
Site build is blocked by invalid wikilinks if d3 graph data is enabled

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#10]
Everything goes smoothly if I disable `d3_graph_data` in `_config.yml`. Nevertheless, if I keep it enabled, I get this:

```
Configuration file: /Users/tommi/tommi.space/_config.yml
            Source: /Users/tommi/tommi.space
       Destination: /Users/tommi/tommi.space/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Net-Web node missing:  così
               in:  La Marmellata
Net-Web node missing:  like this
               in:  The Jam
Net-Web node missing:  Writing#Website
               in:  Website development
Net-Web node missing:  Apps#Nextcloud
               in:  Server setup
Net-Web node missing:  Server setup#Nextcloud configuration|configuration and installation walk-through
               in:  Server
Net-Web node missing:  Linuxplosion#Cheat Sheet
               in:  Cheat sheets
Net-Web node missing:  Vim#Resources
               in:  Knowledge
Net-Web node missing:  The Vignelli Canon
               in:  Typography
Net-Web node missing:  Apps#Android|apps on my Android phone
               in:  Launcher
Net-Web node missing:  Adaptation.
               in:  Parole
Net-Web node missing:  Santa Maradona
               in:  Cinema
Net-Web node missing:  Hotkeys#Firefox|Here
               in:  Firefox
Net-Web node missing:  Film Photography|Film negatives scanning setup
               in:  Wishlist
Net-Web node missing:  iOS Apps|my iPhone
               in:  Bugs and Feature Requests
Net-Web node missing:  Quit Netflix
               in:  Quit and switch
Net-Web node missing:  missing
               in:  Missing Knowledge
Net-Web node missing:  Blaise Pascal
               in:  Notes on Indistractable
Net-Web node missing:  Google Drive and Dropbox shared links
               in:  Quit Google
Net-Web node missing:  Markdown
               in:  Ode to plain text
Net-Web node missing:  Website log#Sidenotes
               in:  Jekyll sidenotes
Net-Web node missing:  Website log#Sidenotes|a great idea
               in:  Website log
Net-Web node missing:  Music idea due
               in:  Music
Net-Web node missing:  Importing workflow#Mobile|import media from my phone
               in:  Linuxplosion
Net-Web node missing:  Hotkeys#Obsidian|Keyboard shortcuts
               in:  Obsidian
Net-Web node missing:  Images
               in:  Geek todo
Net-Web node missing:  Cheat sheets#Terminal|awesome things
               in:  Bash
Net-Web node missing:  Places
               in:  OpenStreetMap
/Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:177:in `write': No such file or directory @ rb_sysopen - /Users/tommi/tommi.space/assets/graph-net-web.json (Errno::ENOENT)
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:177:in `write_graph_data'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-wikilinks-0.0.3/lib/jekyll-wikilinks.rb:58:in `generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:193:in `block in generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:191:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:191:in `generate'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/profiler.rb:43:in `block in profile_process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/profiler.rb:41:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/profiler.rb:41:in `profile_process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:75:in `process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /Users/tommi/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	from /Users/tommi/.rbenv/versions/3.0.1/bin/jekyll:23:in `load'
	from /Users/tommi/.rbenv/versions/3.0.1/bin/jekyll:23:in `<main>'
```

I think it is ok if wikilinks which do not find any destination create warnings at build time, nevertheless, it does not seem usual that the whole build fails because of this.

**Comment by manunamz** [comment]
Do you have an `/assets` directory at the project's root before you start build?

**Comment by xplosionmind** [comment]
Great. I missed (or it is not written) in the documentation the requirement for an `/assets` folder.

I now created it, and everything is working wonderfully.

Nevertheless, I am using the reference to anchors (as mentioned in #2), and warnings continue to appear for those links which should be valid but are not read correctly; I still see `Net-Web node missing` at build time.

**Comment by manunamz** [comment]
Yep! I am currently working on the anchors, so hopefully that will be out soon. 

I might switch those warnings to debug logs too, if that's annoying people.

Side note: Those warnings are really, really useful if people are starving for dangling link detection.

**Comment by xplosionmind** [comment]
> Yep! I am currently working on the anchors, so hopefully that will be out soon.

Yeah! Thank you very much!

<br />

> I might switch those warnings to debug logs too, if that's annoying people.

Don’t. As you pointed out, in some cases to some users they can be tremendously helpful, instead. It is better to have something annoying but useful than not being able to debug some error. Thanks a lot!
