### ISSUE TITLE
Netlify build error

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#21]
I am sorry that errors with Netlify builds continue to happen… this is the error message I get:

```
/opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-wikilinks-0.0.4/lib/jekyll-wikilinks.rb:5:in `require_relative': /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-wikilinks-0.0.4/lib/jekyll-wikilinks/doc_manager.rb:48: syntax error, unexpected ..., expecting ']' (SyntaxError)
... |d| d.basename == filename[...-4] }
...                            ^~~
	from /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-wikilinks-0.0.4/lib/jekyll-wikilinks.rb:5:in `<top (required)>'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler/runtime.rb:66:in `require'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler/runtime.rb:61:in `each'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler/runtime.rb:61:in `block in require'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler/runtime.rb:50:in `each'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler/runtime.rb:50:in `require'
	from /opt/buildhome/.rvm/gems/ruby-2.6.2/gems/bundler-2.2.20/lib/bundler.rb:174:in `require'
	from /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /opt/build/cache/bundle/ruby/2.6.0/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
	from /opt/build/cache/binstubs/jekyll:29:in `load'
	from /opt/build/cache/binstubs/jekyll:29:in `<main>'
```

**Comment by manunamz** [comment]
Fixed (https://github.com/manunamz/jekyll-wikilinks/commit/6e3e51493f32279b0fa9420a56b497696bb799f3) and pushed in v0.0.5.

Let me know if that did the trick.

**Comment by xplosionmind** [comment]
It worked! Thanks a lot ❤️
